//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicMenyBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaProductos
    {
        public int CatID { get; set; }
        public System.DateTime CatFecha { get; set; }
        public string CatNombre { get; set; }
        public int UsuId { get; set; }
        public Nullable<System.DateTime> CatFechaActualizacion { get; set; }
        public string rowid { get; set; }
    
        public virtual CategoriaProductos CategoriaProductos1 { get; set; }
        public virtual CategoriaProductos CategoriaProductos2 { get; set; }
    }
}
