//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicMenyBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprasDetalles
    {
        public int ComID { get; set; }
        public int CdPosicion { get; set; }
        public int ProId { get; set; }
        public int CdCantidad { get; set; }
        public string UsuId { get; set; }
        public Nullable<System.DateTime> CdFechaActualizacion { get; set; }
        public string rowid { get; set; }
    
        public virtual ComprasDetalles ComprasDetalles1 { get; set; }
        public virtual ComprasDetalles ComprasDetalles2 { get; set; }
    }
}
