//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicMenyBind.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebTestContext : DbContext
    {
        public WebTestContext()
            : base("name=WebTestContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CategoriaProductos> CategoriaProductos { get; set; }
        public DbSet<Compras> Compras { get; set; }
        public DbSet<ComprasDetalles> ComprasDetalles { get; set; }
        public DbSet<RolesUsuarios> RolesUsuarios { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<VentasDetalles> VentasDetalles { get; set; }
        public DbSet<Login> Login { get; set; }
        public DbSet<MainMenu> MainMenu { get; set; }
        public DbSet<Productos> Productos { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<SubMenu> SubMenu { get; set; }
        public DbSet<Ventas> Ventas { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
