//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicMenyBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu
    {
        public int SmID { get; set; }
        public string SmName { get; set; }
        public string SmController { get; set; }
        public string SmAction { get; set; }
        public Nullable<int> MenuID { get; set; }
        public Nullable<int> RolID { get; set; }
    }
}
