//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicMenyBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int UsuID { get; set; }
        public System.DateTime UsuFecha { get; set; }
        public string UsuNombre { get; set; }
        public string UsuApellido { get; set; }
        public string UsuClave { get; set; }
        public string UsuEmail { get; set; }
        public int RolID { get; set; }
        public Nullable<System.DateTime> UsuFechaActualizacion { get; set; }
        public string UsuInicioSesion { get; set; }
        public string rowid { get; set; }
    }
}
