//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicMenyBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int VenID { get; set; }
        public System.DateTime VenFecha { get; set; }
        public float Ventotal { get; set; }
        public string UsuId { get; set; }
        public Nullable<decimal> VenDescuento { get; set; }
        public System.DateTime VenFechaActualizacion { get; set; }
        public string rowid { get; set; }
    }
}
