//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicMenyBind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasDetalles
    {
        public int VdId { get; set; }
        public int VdPoscion { get; set; }
        public decimal VenId { get; set; }
        public float VdSubTotal { get; set; }
        public string ProID { get; set; }
        public int Vdcantidad { get; set; }
        public int UsuID { get; set; }
        public string rowid { get; set; }
    }
}
